---
kind: pipeline
type: docker
name: CI/CD 测试

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
  - name: 安装依赖
    image: node:22-alpine
    commands:
      - corepack enable
      - pnpm install --frozen-lockfile

  - name: 代码检查
    image: node:22-alpine
    commands:
      - corepack enable
      - pnpm lint && pnpm format:check

  - name: 构建项目
    image: node:22-alpine
    commands:
      - corepack enable
      - pnpm build
